# Generated by Django 2.2 on 2019-06-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20190621_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='complain_id',
            field=models.CharField(default=122245, max_length=50),
            preserve_default=False,
        ),
    ]
