# Generated by Django 2.2 on 2019-06-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_report_complain_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='enggdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engg_username', models.CharField(max_length=50)),
                ('engg_fullname', models.CharField(max_length=50)),
                ('complainid', models.CharField(max_length=50)),
                ('point', models.IntegerField()),
            ],
        ),
    ]
