# Generated by Django 2.2.2 on 2019-06-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_enggdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='feedbackall',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='feedbackneg',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='feedbackpos',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
