# Generated by Django 2.2.2 on 2019-06-24 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20190624_1423'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='feedbackall',
            new_name='feedbacknul',
        ),
    ]
