# Generated by Django 2.2.2 on 2019-06-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20190624_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fedbackcomp',
            field=models.CharField(default='neutral', max_length=20),
        ),
    ]
