# Generated by Django 2.2.2 on 2019-06-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_report_fedbackcomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fedbackcomp',
            field=models.CharField(default='neutral', max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedbackneg',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedbacknul',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='feedbackpos',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
